/**
 * Coverage report generator.
 *
 * Answers "what is actually for sale where, and what did we fail to read?"
 * straight from the collected data — no hand-maintained tables.
 *
 *   node scripts/coverage.mjs   ->  docs/COVERAGE.md
 *
 * Combined with `validate.mjs`, this is what the weekly freshness automation
 * checks so a market silently regressing to empty is visible.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(new URL("..", import.meta.url).pathname);
const read = (p, fallback) => {
  try {
    return JSON.parse(readFileSync(resolve(root, p), "utf8"));
  } catch {
    return fallback;
  }
};

const latest = read("public/data/latest.json", { records: [], failedSources: [] });
const markets = read("public/data/markets.json", { countries: [] });
const models = read("public/data/models.json", { models: [] });
const config = read("config/sources.json", { sources: [] });

const week = latest.week;
const live = (latest.records ?? []).filter((r) => r.week === week && r.state === "live");
const allModelIds = [...new Set((models.models ?? []).map((m) => m.id))].sort();
const isBody = (m) => /^[ASZMF]\d{2}/.test(m);

const byCountry = new Map();
for (const r of live) {
  const entry = byCountry.get(r.country) ?? { rows: [], models: new Set(), channels: new Set(), sources: new Set(), currencies: new Set() };
  entry.rows.push(r);
  entry.models.add(r.model);
  entry.channels.add(r.channel);
  entry.sources.add(r.sourceId);
  entry.currencies.add(r.currency);
  byCountry.set(r.country, entry);
}

const observed = new Set(live.map((r) => `${r.country}|${r.model}`));
const failed = new Map((latest.failedSources ?? []).map((f) => [f.id, f.error]));
const enabled = config.sources.filter((s) => s.enabled);
const disabled = config.sources.filter((s) => !s.enabled);

const lines = [];
lines.push("# COVERAGE — what is on sale where");
lines.push("");
lines.push(`Generated by \`node scripts/coverage.mjs\` from \`public/data/latest.json\`.`);
lines.push(`Collection week: **${week}** · collected ${latest.collectedAt ?? "n/a"} · FX ${latest.fx?.asOf ?? "n/a"}.`);
lines.push(`**${live.length} live prices** from **${new Set(live.map((r) => r.sourceId)).size} active sources** across **${byCountry.size} markets**.`);
lines.push("");
lines.push("A blank matrix cell means one of two different things, and this file separates them:");
lines.push("");
lines.push("- **not-listed** — no configured source lists that model for that market. Usually a real");
lines.push("  assortment fact (the market does not sell it), but it can also mean every source for that");
lines.push("  market is blocked. Compare with the *blocked sources* section below before concluding.");
lines.push("- **blocked** — a source exists but the fetch/parse failed this run; the failure text is quoted below.");
lines.push("");

lines.push("## Live prices per market");
lines.push("");
lines.push("| Market | Currency | Live prices | Channels | Models with a price | Sources |");
lines.push("|---|---|---:|---|---|---:|");
for (const c of markets.countries ?? []) {
  const e = byCountry.get(c.id);
  lines.push(
    `| ${c.name} \`${c.id}\` | ${e ? [...e.currencies].join("/") : c.currency} | ${e ? e.rows.length : 0} | ${e ? [...e.channels].join(", ") || "—" : "—"} | ${e ? [...e.models].sort().join(", ") : "—"} | ${e ? e.sources.size : 0} |`,
  );
}
lines.push("");

lines.push("## Model × variant observed per market");
lines.push("");
lines.push("| Model | " + (markets.countries ?? []).map((c) => c.id.toUpperCase()).join(" | ") + " |");
lines.push("|---|" + (markets.countries ?? []).map(() => "---").join("|") + "|");
for (const id of allModelIds.filter(isBody)) {
  const cells = (markets.countries ?? []).map((c) => {
    const rows = live.filter((r) => r.country === c.id && r.model === id);
    if (!rows.length) return observed.has(`${c.id}|${id}`) ? "listed" : "not-listed";
    const variants = [...new Set(rows.map((r) => (r.variant === "N/A" ? "?" : r.variant)))].sort();
    return `${variants.join("/")} (${rows.length})`;
  });
  lines.push(`| ${id} | ${cells.join(" | ")} |`);
}
lines.push("");
lines.push("`?` = the listing did not state a storage size · `(n)` = number of live prices · `listed` = a");
lines.push("price exists outside the current week · `not-listed` = no configured source lists it.");
lines.push("");

lines.push("## Enabled sources");
lines.push("");
lines.push("| Source | Market | Channel | Parser | This run |");
lines.push("|---|---|---|---|---|");
for (const s of enabled) {
  const count = live.filter((r) => r.sourceId === s.id).length;
  lines.push(
    `| \`${s.id}\` | ${s.country} | ${s.channel} | \`${s.parser}\` | ${failed.has(s.id) ? `**blocked** — ${String(failed.get(s.id)).slice(0, 100)}` : `${count} live`} |`,
  );
}
lines.push("");

if (disabled.length) {
  lines.push("## Disabled sources (no verified price yet)");
  lines.push("");
  for (const s of disabled) {
    lines.push(`- \`${s.id}\` (${s.country}) — ${s.disabledReason ?? "no reason recorded"}`);
  }
  lines.push("");
}

if (latest.failedSources?.length) {
  lines.push("## Blocked this run");
  lines.push("");
  lines.push("These are recorded as failures, never as a price or a carry-forward guess.");
  lines.push("");
  for (const f of latest.failedSources) lines.push(`- \`${f.id}\` (${f.country}) — ${String(f.error).slice(0, 200)}`);
  lines.push("");
}

lines.push("## Sources of evidence");
lines.push("");
lines.push("Every row above is backed by a record carrying `sourceId`, `sourceUrl`, `collectedAt` and");
lines.push("`rawEvidence`; `node scripts/validate.mjs` enforces that. Per-record links live in the");
lines.push("`价格记录` panel of the site and in `public/data/latest.json`.");
lines.push("");

writeFileSync(resolve(root, "docs/COVERAGE.md"), `${lines.join("\n")}\n`);
console.log(`docs/COVERAGE.md written: ${live.length} live prices across ${byCountry.size} markets, ${allModelIds.filter(isBody).length} models, ${latest.failedSources?.length ?? 0} blocked sources.`);
